default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: citadel_dev
  password: foobar
  host: localhost
  port: 5432

development:
  <<: *default
  database: citadel_0

test:
  <<: *default
  database: citadel_1

production:
  <<: *default
  database: citadel_2