default: &default
  # topic or none
  type: none
  # id of the topic to take news from. Optional if type is none
  id: none
  # Number of recent threads to display. Optional if type is none
  display: none

development:
  <<: *default
  database: citadel_dev

test:
  <<: *default
  database: citadel_test

production:
  <<: *default
  database: citadel_prod
